tfc_org                      = "wellsiau-org"
aws_region                   = "us-west-2"
runtask_id                   = "task-PxfajvmqKhdwjf3V"
demo_workspace_name          = "aws-ia2-workspace"
flag_attach_runtask          = "true"
flag_deploy_invalid_resource = "true"
