diff a/.project_automation/static_tests/Dockerfile b/.project_automation/static_tests/Dockerfile	(rejected hunks)
@@ -23 +23,5 @@ RUN curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/
 RUN gem install mdl
+
+ENV TERRAFORM_DOCS_VERSION=v0.16.0
+RUN wget https://github.com/terraform-docs/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz && \
+    tar -C /usr/local/bin -xzf terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz && chmod +x /usr/local/bin/terraform-docs
\ No newline at end of file
